name: ubu_ign

services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: dockerfile.mosquitto
    container_name: mosquitto_broker
    env_file:
      - secret.env
    #entrypoint: ["/mosquitto/entrypoint.sh"]
    restart: always
    ports:
      # <puerto_host>:<puerto_contenedor>
      - "1883:1883" # MQTT
      - "9001:9001" # Websocket
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      # - "./mosquitto/data:/mosquitto/data"
      # - "./mosquitto/log:/mosquitto/log"